
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./models:/models
      - ./build_models.sh:/build_models.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
    entrypoint: ["/bin/bash", "-c"]
    command: ["ollama serve & /build_models.sh && wait"]

volumes:
  ollama:
